-- =====================================================================
-- Jardim Vivo — catálogo inicial de espécies (orientação oficial)
-- Intervalos são apenas lembretes para VERIFICAR; a decisão de regar ou
-- adubar deve sempre considerar o substrato e a condição da planta.
-- =====================================================================

insert into public.plant_species
  (owner_id, nome_comum, nome_cientifico, familia, descricao, origem, dificuldade,
   luminosidade, rega, intervalo_verificacao_rega_dias, substrato, adubacao, intervalo_adubacao_dias,
   temperatura, poda, transplante, floracao, colheita, dias_ate_colheita, pragas, deficiencias,
   estagios, usos, dica)
values
(null, 'Manjericão', 'Ocimum basilicum', 'Lamiaceae',
 'Erva aromática de folhas macias e perfumadas, muito usada na cozinha.',
 'Regiões tropicais da Ásia e África.', 'fácil',
 'Sol pleno ou pelo menos 4–6 h de sol direto.',
 'Manter o substrato levemente úmido, sem encharcar. Verifique com o dedo: regue quando os 2 cm de cima estiverem secos.', 2,
 'Substrato leve, rico em matéria orgânica e bem drenado.',
 'Húmus de minhoca ou composto orgânico a cada 30 dias, em pequena quantidade.', 30,
 'Prefere 18–30 °C; sofre com frio e geada.',
 'Belisque as pontas acima de um par de folhas para ramificar. Retire os botões florais para prolongar a produção de folhas.',
 'Transplante quando a muda tiver 4–6 folhas verdadeiras.',
 'Floresce no verão; a floração reduz o sabor das folhas.',
 'Colha as folhas de cima para baixo, sempre deixando folhas na planta.', 60,
 'Pulgões, mosca-branca, lagartas e fungos por excesso de umidade.',
 'Folhas amareladas por baixo podem indicar falta de nitrogênio ou excesso de água.',
 'Semente → germinação (5–10 dias) → muda → crescimento → floração.',
 'Culinária (molhos, saladas, pesto). Atrai polinizadores quando floresce.',
 'Não regue as folhas no fim da tarde: isso favorece fungos.'),

(null, 'Alecrim', 'Salvia rosmarinus', 'Lamiaceae',
 'Arbusto aromático de folhas finas, muito resistente.',
 'Região do Mediterrâneo.', 'fácil',
 'Sol pleno, o máximo possível.',
 'Pouca água. Regue só quando o substrato estiver seco; o encharcamento é a principal causa de perda.', 4,
 'Substrato arenoso e muito bem drenado; evite pratinho com água.',
 'Pouca adubação: composto ou húmus a cada 60 dias.', 60,
 'Tolera calor e frio moderado.',
 'Poda leve após a floração para manter a forma; não corte a parte lenhosa sem folhas.',
 'Transplante para vaso maior quando as raízes saírem pelo furo.',
 'Pequenas flores azuladas no inverno/primavera.',
 'Colha ramos com tesoura limpa, até 1/3 da planta por vez.', 90,
 'Cochonilhas e podridão de raiz por excesso de água.',
 'Folhas escurecendo na base geralmente indicam excesso de água, não falta de adubo.',
 'Estaca/semente → enraizamento → muda → arbusto.',
 'Culinária e aromatização.',
 'Se ficar em dúvida, espere mais um dia para regar.'),

(null, 'Tomate', 'Solanum lycopersicum', 'Solanaceae',
 'Hortaliça-fruto de ciclo anual, muito cultivada em hortas e vasos grandes.',
 'Região andina da América do Sul.', 'média',
 'Sol pleno: 6–8 h de sol direto.',
 'Rega regular e uniforme, no pé da planta. Variações bruscas de umidade causam rachaduras e fundo preto nos frutos.', 1,
 'Substrato fértil, com bastante matéria orgânica, em vaso de pelo menos 20 L.',
 'Composto ou húmus a cada 15–20 dias; na frutificação, adubo rico em potássio e cálcio.', 20,
 'Ideal 20–28 °C.',
 'Retire os brotos laterais (ladrões) nas variedades de crescimento indeterminado. Use tutor.',
 'Transplante quando a muda tiver 4–6 folhas, enterrando um pouco do caule.',
 'Flores amarelas aparecem cerca de 45–60 dias após a semeadura.',
 'Colha quando o fruto estiver com cor uniforme e levemente macio.', 90,
 'Traça-do-tomateiro, pulgões, mosca-branca, requeima e pinta-preta.',
 'Fundo preto no fruto: irregularidade de rega/cálcio. Folhas velhas amarelas: possível falta de nitrogênio.',
 'Semente → germinação (5–10 dias) → muda → crescimento → floração → frutificação → colheita.',
 'Culinária.',
 'Regue sempre no solo, não nas folhas, para reduzir doenças.'),

(null, 'Pimenta Dedo-de-Moça', 'Capsicum baccatum', 'Solanaceae',
 'Pimenta de ardência média, frutos alongados e vermelhos quando maduros.',
 'América do Sul.', 'fácil',
 'Sol pleno.',
 'Manter levemente úmido; tolera pequenos períodos de seca melhor que o encharcamento.', 2,
 'Substrato fértil e bem drenado, vaso de 10 L ou mais.',
 'Húmus ou composto a cada 30 dias.', 30,
 'Gosta de calor; 20–30 °C.',
 'Poda de limpeza após a colheita para renovar a planta.',
 'Transplante com 4–6 folhas definitivas.',
 'Flores brancas pequenas; cada flor pode virar um fruto.',
 'Colha quando os frutos estiverem totalmente vermelhos.', 100,
 'Pulgões, ácaros e mosca-branca.',
 'Queda de flores pode indicar calor extremo, falta de água ou falta de polinização.',
 'Semente → germinação (10–20 dias) → muda → crescimento → floração → frutificação.',
 'Culinária. Manuseie com cuidado e lave as mãos após cortar.',
 'Mexa levemente os galhos floridos para ajudar a polinização em locais sem insetos.'),

(null, 'Alface', 'Lactuca sativa', 'Asteraceae',
 'Hortaliça folhosa de ciclo rápido.',
 'Região do Mediterrâneo.', 'fácil',
 'Sol da manhã ou meia-sombra no calor forte.',
 'Rega frequente e leve; não deixe o substrato secar por completo.', 1,
 'Substrato leve, fofo e rico em matéria orgânica.',
 'Húmus a cada 15 dias.', 15,
 'Prefere clima ameno (15–24 °C); no calor tende a pendoar e amargar.',
 'Não precisa de poda; retire folhas velhas ou danificadas.',
 'Transplante quando a muda tiver 4–5 folhas.',
 'Ao florescer (pendoar), as folhas ficam amargas.',
 'Colha a planta inteira ou folhas externas conforme a necessidade.', 50,
 'Lesmas, pulgões e lagartas.',
 'Pontas queimadas: falta de água ou calor excessivo.',
 'Semente → germinação (3–7 dias) → muda → crescimento → colheita.',
 'Culinária (saladas).',
 'Semeie um pouco a cada 2–3 semanas para ter colheita contínua.'),

(null, 'Cebolinha', 'Allium fistulosum', 'Amaryllidaceae',
 'Tempero de folhas tubulares, rebrota após o corte.',
 'Ásia.', 'fácil',
 'Sol pleno ou meia-sombra.',
 'Manter úmido sem encharcar.', 2,
 'Substrato fértil e drenado.',
 'Húmus a cada 30 dias, principalmente após cortes.', 30,
 'Tolera ampla faixa de temperatura.',
 'Corte as folhas a 3–5 cm do solo para estimular a rebrota.',
 'Divida as touceiras quando o vaso ficar cheio.',
 'Flores brancas em bolinhas; retire para prolongar as folhas.',
 'Colha cortando as folhas externas.', 60,
 'Tripes e fungos por excesso de umidade.',
 'Pontas amarelas podem indicar falta de nitrogênio ou água irregular.',
 'Semente/touceira → muda → crescimento → cortes sucessivos.',
 'Culinária.',
 'Colher com frequência estimula a planta.'),

(null, 'Salsa', 'Petroselinum crispum', 'Apiaceae',
 'Tempero de folhas recortadas, de crescimento lento no início.',
 'Região do Mediterrâneo.', 'média',
 'Sol da manhã ou meia-sombra.',
 'Manter levemente úmido.', 2,
 'Substrato fértil, profundo e drenado.',
 'Húmus a cada 30 dias.', 30,
 'Prefere clima ameno.',
 'Colha os talos externos rente à base.',
 'Não gosta de transplante; prefira semear no local definitivo.',
 'Floresce no segundo ano e depois encerra o ciclo.',
 'Colha talos externos quando a planta tiver muitas folhas.', 75,
 'Pulgões e lagartas.',
 'Folhas amareladas: possível falta de nitrogênio ou excesso de sol forte.',
 'Semente → germinação lenta (15–30 dias) → muda → crescimento.',
 'Culinária.',
 'Deixe as sementes de molho por 12 h antes de semear para acelerar a germinação.'),

(null, 'Hortelã', 'Mentha spicata', 'Lamiaceae',
 'Erva aromática vigorosa que se espalha por estolões.',
 'Europa e Ásia.', 'fácil',
 'Meia-sombra ou sol da manhã.',
 'Gosta de umidade constante.', 1,
 'Substrato rico em matéria orgânica.',
 'Húmus a cada 30 dias.', 30,
 'Tolera frio e calor moderados.',
 'Pode com frequência para manter compacta.',
 'Cultive sozinha no vaso: ela compete com outras plantas.',
 'Pequenas flores lilases no verão.',
 'Colha as pontas dos ramos.', 45,
 'Ferrugem (pontos alaranjados), pulgões e ácaros.',
 'Folhas pequenas e pálidas: falta de luz ou nutrientes.',
 'Estaca/muda → enraizamento → crescimento.',
 'Culinária, chás e bebidas.',
 'Enraíza facilmente em um copo com água.'),

(null, 'Morango', 'Fragaria × ananassa', 'Rosaceae',
 'Planta rasteira que produz frutos doces e emite estolões.',
 'Híbrido desenvolvido na Europa.', 'média',
 'Sol pleno ou pelo menos 6 h de sol.',
 'Manter úmido, regando no solo; evite molhar os frutos.', 1,
 'Substrato leve, ácido e bem drenado.',
 'Composto/húmus a cada 20 dias; na frutificação, adubo rico em potássio.', 20,
 'Prefere clima ameno (15–25 °C).',
 'Retire folhas secas e estolões se quiser priorizar frutos.',
 'Plante as mudas com a coroa no nível do substrato.',
 'Flores brancas na primavera.',
 'Colha frutos totalmente vermelhos.', 90,
 'Lesmas, ácaros, pássaros e mofo-cinzento.',
 'Folhas avermelhadas podem indicar frio ou falta de fósforo.',
 'Muda/estolão → enraizamento → floração → frutificação.',
 'Culinária.',
 'Use palha ou casca de pinus sob os frutos para não encostarem no solo úmido.'),

(null, 'Babosa', 'Aloe vera', 'Asphodelaceae',
 'Suculenta de folhas carnudas que armazenam água.',
 'Península Arábica.', 'fácil',
 'Sol pleno ou muita claridade.',
 'Pouca água: regue só quando o substrato estiver completamente seco.', 7,
 'Substrato para cactos e suculentas, muito drenado.',
 'Raramente precisa; composto leve a cada 90 dias na primavera/verão.', 90,
 'Não tolera geada.',
 'Retire folhas secas na base.',
 'Separe os filhotes que nascem ao redor quando tiverem algumas folhas.',
 'Pode emitir haste com flores tubulares em plantas adultas.',
 'Não se aplica.', null,
 'Cochonilhas e podridão por excesso de água.',
 'Folhas finas e enrugadas: falta de água. Folhas moles e escuras: excesso de água.',
 'Muda/filhote → crescimento → planta adulta.',
 'Ornamental. Uso medicinal somente com orientação profissional.',
 'Folhas avermelhadas costumam indicar sol muito forte ou estresse.'),

(null, 'Coentro', 'Coriandrum sativum', 'Apiaceae',
 'Erva de ciclo rápido, folhas e sementes aromáticas.',
 'Região do Mediterrâneo e Oriente Médio.', 'média',
 'Sol da manhã ou meia-sombra no calor intenso.',
 'Manter levemente úmido.', 1,
 'Substrato leve e fértil.',
 'Húmus a cada 20 dias.', 20,
 'Pendoa rápido no calor forte.',
 'Colha folhas externas com frequência.',
 'Não gosta de transplante; semeie no local definitivo.',
 'Flores brancas que viram sementes (coentro em grão).',
 'Colha folhas a partir de 30–40 dias.', 40,
 'Pulgões.',
 'Amarelamento geral: falta de nutrientes ou excesso de água.',
 'Semente → germinação (7–14 dias) → crescimento → floração → sementes.',
 'Culinária.',
 'Quebre levemente a semente (que é um fruto com duas sementes) antes de plantar.'),

(null, 'Rúcula', 'Eruca vesicaria', 'Brassicaceae',
 'Folhosa de sabor picante e ciclo curto.',
 'Região do Mediterrâneo.', 'fácil',
 'Sol ou meia-sombra.',
 'Manter úmido.', 1,
 'Substrato fértil e leve.',
 'Húmus a cada 15 dias.', 15,
 'Prefere clima ameno.',
 'Colha folhas externas.',
 'Semeie direto no vaso; desbaste deixando 5–10 cm entre plantas.',
 'Flores claras; após florescer, folhas ficam mais picantes.',
 'Colha a partir de 30 dias.', 35,
 'Pulgão e besouros que furam as folhas.',
 'Folhas pálidas: falta de nitrogênio.',
 'Semente → germinação (3–5 dias) → crescimento → colheita.',
 'Culinária.',
 'Mudas muito juntas competem: desbaste cedo.')
on conflict do nothing;
